apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: httpd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        resources:
          limits:
            cpu: 600m
            #ram: 256Mi
          requests:
            cpu: 100m
            #ram: 128Mi
      nodeSelector: 
        type: "ec2"   
status: {}
